services:
  db:
    image: postgres:16-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT_EXTERNAL}:${DB_PORT}"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app
    ports:
      - "8081:8080"
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      SSL_MODE: ${SSL_MODE}
      CLOUDINARY_NAME_KEY: ${CLOUDINARY_NAME_KEY}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_SECRET_KEY: ${CLOUDINARY_SECRET_KEY}
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  postgres_data:
